#include "web.h"

static const char * const html_dashboard =
"<!DOCTYPE html>\n"
"<html lang='en'>\n"
"<head>\n"
"<meta charset='UTF-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1.0'>\n"
"<meta name='theme-color' content='#f6fbff'>\n"
"<title>Solo Mining Server</title>\n"
"<style>\n"
":root{--bg-a:#f8fcff;--bg-b:#eef5ff;--bg-c:#fff6eb;--text:#17324d;--muted:#61758e;--soft:#90a2b6;--line:rgba(23,50,77,0.12);--panel:rgba(255,255,255,0.78);--panel-strong:rgba(255,255,255,0.94);--accent:#1d8cf8;--accent-2:#ff7a59;--accent-3:#f6ae2d;--accent-4:#18b7a0;--shadow:0 28px 70px rgba(39,67,104,0.14)}\n"
"*{box-sizing:border-box}\n"
"html{color-scheme:light}\n"
"body{margin:0;min-height:100vh;font-family:'Avenir Next','Trebuchet MS','Segoe UI Variable','Segoe UI',sans-serif;color:var(--text);background:linear-gradient(180deg,var(--bg-a) 0%,var(--bg-b) 54%,var(--bg-c) 100%);-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}\n"
"body::before,body::after{content:'';position:fixed;inset:auto;pointer-events:none;z-index:0}\n"
"body::before{top:-140px;left:-120px;width:420px;height:420px;border-radius:50%;background:radial-gradient(circle,rgba(29,140,248,0.17),transparent 70%)}\n"
"body::after{right:-100px;bottom:-140px;width:460px;height:460px;border-radius:50%;background:radial-gradient(circle,rgba(255,122,89,0.14),transparent 72%)}\n"
".page{position:relative;z-index:1;max-width:1360px;margin:0 auto;padding:24px 16px 40px}\n"
".shell{position:relative;background:rgba(255,255,255,0.68);border:1px solid rgba(255,255,255,0.9);border-radius:32px;padding:24px;box-shadow:var(--shadow);-webkit-backdrop-filter:blur(18px);backdrop-filter:blur(18px)}\n"
"@supports not ((-webkit-backdrop-filter:blur(1px)) or (backdrop-filter:blur(1px))){.shell{background:rgba(255,255,255,0.95)}}\n"
".topbar{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(320px,0.95fr);gap:18px;align-items:start}\n"
".brand{padding:6px 2px}\n"
".kicker{font-size:11px;letter-spacing:0.22em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".brand h1{margin:10px 0 10px;font-size:40px;line-height:1.04;font-weight:800;letter-spacing:-0.04em}\n"
".brand h1 span{display:block;color:var(--accent-2)}\n"
".brand p{margin:0;max-width:680px;font-size:16px;line-height:1.65;color:var(--muted)}\n"
".status-board{position:relative;overflow:hidden;background:linear-gradient(145deg,rgba(29,140,248,0.15),rgba(255,255,255,0.9) 56%,rgba(24,183,160,0.12));border:1px solid rgba(29,140,248,0.16);border-radius:26px;padding:18px 18px 16px;box-shadow:0 18px 40px rgba(46,79,120,0.11)}\n"
".status-board.warn{background:linear-gradient(145deg,rgba(246,174,45,0.2),rgba(255,255,255,0.92) 56%,rgba(255,122,89,0.1));border-color:rgba(246,174,45,0.24)}\n"
".status-board.danger{background:linear-gradient(145deg,rgba(255,122,89,0.18),rgba(255,255,255,0.92) 56%,rgba(246,174,45,0.12));border-color:rgba(255,122,89,0.24)}\n"
".status-row{display:flex;align-items:center;gap:14px}\n"
".status-dot{width:14px;height:14px;border-radius:999px;background:var(--accent);box-shadow:0 0 0 6px rgba(29,140,248,0.12),0 0 18px rgba(29,140,248,0.4);flex:0 0 auto}\n"
".status-dot.warn{background:var(--accent-3);box-shadow:0 0 0 6px rgba(246,174,45,0.16),0 0 18px rgba(246,174,45,0.35)}\n"
".status-dot.danger{background:var(--accent-2);box-shadow:0 0 0 6px rgba(255,122,89,0.14),0 0 18px rgba(255,122,89,0.35)}\n"
".status-copy strong{display:block;font-size:18px;font-weight:800}\n"
".status-copy span{display:block;margin-top:4px;color:var(--muted);font-size:14px;line-height:1.45}\n"
".meta-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:16px}\n"
".meta-pill{background:rgba(255,255,255,0.78);border:1px solid rgba(23,50,77,0.1);border-radius:18px;padding:12px 12px 10px}\n"
".meta-label{display:block;margin-bottom:6px;font-size:10px;letter-spacing:0.13em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".meta-pill strong{display:block;font-size:14px;font-weight:800;word-break:break-word}\n"
".hero-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px;margin-top:24px}\n"
".hero-card{position:relative;overflow:hidden;background:var(--panel);border:1px solid var(--line);border-radius:24px;padding:20px 20px 18px;box-shadow:0 14px 28px rgba(41,73,113,0.08)}\n"
".hero-card::before{content:'';position:absolute;right:-48px;top:-58px;width:180px;height:180px;border-radius:50%;opacity:.66;pointer-events:none}\n"
".hero-card.accent-blue::before{background:radial-gradient(circle,rgba(61,123,251,0.24),transparent 70%)}\n"
".hero-card.accent-coral::before{background:radial-gradient(circle,rgba(255,122,89,0.2),transparent 70%)}\n"
".hero-card.accent-gold::before{background:radial-gradient(circle,rgba(246,174,45,0.24),transparent 70%)}\n"
".hero-card.accent-teal::before{background:radial-gradient(circle,rgba(24,183,160,0.2),transparent 70%)}\n"
".hero-top{display:flex;justify-content:space-between;align-items:center;gap:12px}\n"
".eyebrow{font-size:11px;letter-spacing:0.14em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".micro-badge{display:inline-flex;align-items:center;padding:7px 10px;border-radius:999px;background:rgba(255,255,255,0.85);border:1px solid rgba(23,50,77,0.1);font-size:11px;color:var(--muted);font-weight:700;white-space:nowrap}\n"
".hero-value{margin-top:18px;font-size:36px;font-weight:800;letter-spacing:-0.04em;line-height:1.04}\n"
".hero-unit{margin-top:8px;font-size:13px;color:var(--muted)}\n"
".hero-meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}\n"
".hero-meta span{display:block;margin-bottom:4px;font-size:10px;letter-spacing:0.12em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".hero-meta strong{display:block;font-size:14px;line-height:1.45;word-break:break-word}\n"
".metric-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:14px;margin-top:16px}\n"
".metric-card{background:var(--panel);border:1px solid var(--line);border-radius:20px;padding:16px 16px 14px;box-shadow:0 10px 24px rgba(41,73,113,0.07)}\n"
".metric-card .label{font-size:10px;letter-spacing:0.14em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".metric-card .value{margin-top:10px;font-size:22px;font-weight:800;letter-spacing:-0.03em;line-height:1.2}\n"
".metric-card .sub{margin-top:8px;font-size:12px;color:var(--muted);line-height:1.45}\n"
".detail-grid{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(300px,0.9fr);gap:16px;margin-top:18px}\n"
".panel{background:var(--panel);border:1px solid var(--line);border-radius:24px;padding:20px;box-shadow:0 12px 26px rgba(41,73,113,0.08)}\n"
".panel-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:14px}\n"
".panel-head h2{margin:0;font-size:18px;font-weight:800}\n"
".panel-head p{margin:6px 0 0;font-size:13px;line-height:1.55;color:var(--muted)}\n"
".health-group+.health-group{margin-top:14px;padding-top:14px;border-top:1px solid rgba(23,50,77,0.08)}\n"
".health-top{display:flex;justify-content:space-between;align-items:center;gap:12px}\n"
".health-top span{font-size:13px;font-weight:700}\n"
".health-top strong{font-size:14px;font-weight:800}\n"
".progress{height:10px;background:rgba(29,140,248,0.1);border-radius:999px;overflow:hidden;margin-top:10px}\n"
".progress span{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--accent),var(--accent-4));border-radius:999px;transition:width .3s ease}\n"
".health-note{margin:10px 0 0;font-size:12px;line-height:1.55;color:var(--muted)}\n"
".spotlight-panel{background:linear-gradient(160deg,rgba(29,140,248,0.12),rgba(255,255,255,0.94) 44%,rgba(24,183,160,0.08))}\n"
".best-share{display:grid;gap:16px}\n"
".best-share-top span{display:block;font-size:10px;letter-spacing:0.14em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".best-share-top strong{display:block;margin-top:10px;font-size:34px;line-height:1.04;letter-spacing:-0.04em;word-break:break-word}\n"
".best-share-meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}\n"
".best-share-meta span{display:block;font-size:10px;letter-spacing:0.12em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".best-share-meta strong{display:block;margin-top:6px;font-size:14px;line-height:1.45;word-break:break-word}\n"
".section{margin-top:22px}\n"
".section-head{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;margin-bottom:14px}\n"
".section-kicker{font-size:10px;letter-spacing:0.16em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".section-head h2{margin:6px 0 0;font-size:20px;font-weight:800}\n"
".section-head p{margin:0;font-size:13px;color:var(--muted);line-height:1.45}\n"
".section-meta{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:10px}\n"
".section-pill{display:inline-flex;align-items:center;padding:8px 12px;border-radius:999px;background:rgba(255,255,255,0.86);border:1px solid rgba(23,50,77,0.1);font-size:12px;font-weight:700;color:var(--text)}\n"
".section-pill.muted{font-weight:600;color:var(--muted)}\n"
".worker-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}\n"
".worker-card{background:var(--panel-strong);border:1px solid var(--line);border-radius:22px;padding:18px;box-shadow:0 12px 22px rgba(41,73,113,0.07)}\n"
".worker-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}\n"
".rank{font-size:11px;letter-spacing:0.12em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".worker-card h3{margin:6px 0 0;font-size:18px;line-height:1.2;font-weight:800}\n"
".badge-soft{display:inline-flex;align-items:center;padding:7px 10px;border-radius:999px;background:rgba(29,140,248,0.1);color:var(--accent);font-size:12px;font-weight:700;white-space:nowrap}\n"
".worker-agent{margin:12px 0 0;min-height:40px;font-size:13px;line-height:1.5;color:var(--muted);word-break:break-word}\n"
".meter{height:8px;background:rgba(23,50,77,0.08);border-radius:999px;overflow:hidden;margin-top:14px}\n"
".meter span{display:block;height:100%;background:linear-gradient(90deg,var(--accent),var(--accent-2));border-radius:999px}\n"
".worker-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:14px}\n"
".worker-stats span{display:block;font-size:10px;letter-spacing:0.12em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".worker-stats strong{display:block;margin-top:5px;font-size:15px;line-height:1.4;word-break:break-word}\n"
".share-list{display:grid;gap:10px}\n"
".share-strip{display:grid;grid-template-columns:minmax(0,1.35fr) repeat(3,minmax(110px,0.62fr)) minmax(138px,0.78fr);gap:12px;align-items:center;background:var(--panel-strong);border:1px solid var(--line);border-radius:18px;padding:10px 14px;box-shadow:0 10px 18px rgba(41,73,113,0.06)}\n"
".share-strip-main{min-width:0}\n"
".share-strip-title{font-size:15px;font-weight:800;line-height:1.25}\n"
".share-strip-sub{display:block;margin-top:3px;font-size:12px;line-height:1.4;color:var(--muted);word-break:break-word}\n"
".share-strip-stat span{display:block;font-size:10px;letter-spacing:0.12em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".share-strip-stat strong{display:block;margin-top:5px;font-size:14px;line-height:1.35;word-break:break-word}\n"
".share-strip-time{font-size:12px;text-align:right;white-space:nowrap;color:var(--muted);line-height:1.4}\n"
".feed-list{display:grid;gap:14px}\n"
".feed-item{background:var(--panel-strong);border:1px solid var(--line);border-radius:22px;padding:18px;box-shadow:0 12px 22px rgba(41,73,113,0.07)}\n"
".feed-top{display:flex;justify-content:space-between;align-items:flex-start;gap:14px}\n"
".feed-title{font-size:17px;font-weight:800;line-height:1.3}\n"
".feed-sub{display:block;margin-top:5px;font-size:13px;line-height:1.5;color:var(--muted);word-break:break-word}\n"
".feed-time{font-size:12px;text-align:right;white-space:nowrap;color:var(--muted);line-height:1.5}\n"
".feed-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:16px}\n"
".feed-grid .wide{grid-column:span 2}\n"
".feed-grid span{display:block;font-size:10px;letter-spacing:0.12em;text-transform:uppercase;color:var(--soft);font-weight:700}\n"
".feed-grid strong{display:block;margin-top:6px;font-size:15px;line-height:1.45;word-break:break-word}\n"
".status-pill{display:inline-flex;align-items:center;padding:7px 10px;border-radius:999px;font-size:12px;font-weight:700}\n"
".status-pill.ok{background:rgba(24,183,160,0.12);color:var(--accent-4)}\n"
".status-pill.warn{background:rgba(246,174,45,0.18);color:#a46a00}\n"
".status-pill.danger{background:rgba(255,122,89,0.14);color:var(--accent-2)}\n"
".code{font-family:'SF Mono','Cascadia Code','Consolas','Liberation Mono',monospace;font-variant-numeric:tabular-nums}\n"
".empty-state{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;min-height:160px;padding:28px;text-align:center;border:1px dashed rgba(23,50,77,0.16);border-radius:22px;background:rgba(255,255,255,0.58);color:var(--muted)}\n"
".empty-state strong{font-size:16px;color:var(--text)}\n"
".foot{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-top:24px;padding-top:18px;border-top:1px solid rgba(23,50,77,0.08);font-size:12px;color:var(--muted)}\n"
".hero-card,.metric-card,.panel,.worker-card,.share-strip,.feed-item,.meta-pill,.section-pill{transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}\n"
".hero-card:hover,.metric-card:hover,.panel:hover,.worker-card:hover,.share-strip:hover,.feed-item:hover,.meta-pill:hover,.section-pill:hover{transform:translateY(-2px);box-shadow:0 18px 32px rgba(41,73,113,0.1)}\n"
"@media(min-width:1120px){.hero-card-lg{grid-column:span 2}}\n"
"@media(max-width:1120px){.topbar{grid-template-columns:1fr}}\n"
"@media(max-width:900px){.detail-grid{grid-template-columns:1fr}.section-head{flex-direction:column;align-items:flex-start}.section-meta{justify-content:flex-start}.best-share-meta{grid-template-columns:1fr}.share-strip{grid-template-columns:repeat(2,minmax(0,1fr))}.share-strip-main,.share-strip-time{grid-column:1/-1}.share-strip-time{text-align:left;white-space:normal}}\n"
"@media(max-width:680px){.page{padding:14px 10px 24px}.shell{padding:16px;border-radius:24px}.brand h1{font-size:32px}.meta-grid{grid-template-columns:1fr}.hero-meta{grid-template-columns:1fr}.worker-stats,.feed-grid{grid-template-columns:1fr}.feed-grid .wide{grid-column:auto}.feed-top{flex-direction:column}.feed-time{text-align:left;white-space:normal}.best-share-top strong{font-size:28px}}\n"
"@media(max-width:540px){.hero-grid,.metric-grid,.worker-grid,.share-strip{grid-template-columns:1fr}.hero-value{font-size:30px}.metric-card .value{font-size:20px}.share-strip-main,.share-strip-time{grid-column:auto}}\n"
"@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class='page'>\n"
"  <div class='shell'>\n"
"    <header class='topbar'>\n"
"      <div class='brand'>\n"
"        <div class='kicker'>Embedded Dashboard</div>\n"
"        <h1>Solo Mining<span>Operational View</span></h1>\n"
"        <p>Live visibility for template health, worker activity, share quality, and block submission results from the built-in HTTP API.</p>\n"
"      </div>\n"
"      <aside class='status-board' id='status-board'>\n"
"        <div class='status-row'>\n"
"          <span class='status-dot' id='status-dot'></span>\n"
"          <div class='status-copy'>\n"
"            <strong id='status-text'>Connecting...</strong>\n"
"            <span id='status-note'>Waiting for the first dashboard snapshot.</span>\n"
"          </div>\n"
"        </div>\n"
"        <div class='meta-grid'>\n"
"          <div class='meta-pill'><span class='meta-label'>Gateway</span><strong id='v-ver'>--</strong></div>\n"
"          <div class='meta-pill'><span class='meta-label'>Last Refresh</span><strong id='v-refresh-meta'>--</strong></div>\n"
"          <div class='meta-pill'><span class='meta-label'>Auto Poll</span><strong>5 seconds</strong></div>\n"
"        </div>\n"
"      </aside>\n"
"    </header>\n"
"    <section class='hero-grid'>\n"
"      <article class='hero-card hero-card-lg accent-blue'>\n"
"        <div class='hero-top'><span class='eyebrow'>Total Hashrate</span><span class='micro-badge'>Live TH/s</span></div>\n"
"        <div class='hero-value code' id='v-hash'>--</div>\n"
"        <div class='hero-unit'>Estimated subscribed fleet hashrate</div>\n"
"        <div class='hero-meta'>\n"
"          <div><span>Average Per Worker</span><strong id='v-hash-sub'>Waiting for workers</strong></div>\n"
"          <div><span>Share Decisions</span><strong id='v-hash-note'>No share history yet</strong></div>\n"
"        </div>\n"
"      </article>\n"
"      <article class='hero-card accent-coral'>\n"
"        <div class='hero-top'><span class='eyebrow'>Subscribed Workers</span><span class='micro-badge'>Stratum</span></div>\n"
"        <div class='hero-value code' id='v-workers'>--</div>\n"
"        <div class='hero-unit'>Active miners broadcasting metrics</div>\n"
"        <div class='hero-meta'>\n"
"          <div><span>Socket Connections</span><strong id='v-workers-sub'>--</strong></div>\n"
"          <div><span>Connection Coverage</span><strong id='v-workers-note'>--</strong></div>\n"
"        </div>\n"
"      </article>\n"
"      <article class='hero-card accent-gold'>\n"
"        <div class='hero-top'><span class='eyebrow'>Current Template</span><span class='micro-badge'>Block Height</span></div>\n"
"        <div class='hero-value code' id='v-height'>--</div>\n"
"        <div class='hero-unit'>Current mining job height</div>\n"
"        <div class='hero-meta'>\n"
"          <div><span>Template Transactions</span><strong id='v-height-sub'>--</strong></div>\n"
"          <div><span>Template Age</span><strong id='v-height-note'>--</strong></div>\n"
"        </div>\n"
"      </article>\n"
"      <article class='hero-card accent-teal'>\n"
"        <div class='hero-top'><span class='eyebrow'>Network Hashrate</span><span class='micro-badge'>Bitcoind</span></div>\n"
"        <div class='hero-value code' id='v-reward'>--</div>\n"
"        <div class='hero-unit'>Bitcoind reported network hashrate</div>\n"
"        <div class='hero-meta'>\n"
"          <div><span>Template Value</span><strong id='v-reward-sub'>--</strong></div>\n"
"          <div><span>Process Uptime</span><strong id='v-reward-note'>--</strong></div>\n"
"        </div>\n"
"      </article>\n"
"    </section>\n"
"    <section class='metric-grid'>\n"
"      <article class='metric-card'><div class='label'>Connected Sockets</div><div class='value code' id='m-sockets'>--</div><div class='sub' id='m-sockets-sub'>Open Stratum connections</div></article>\n"
"      <article class='metric-card'><div class='label'>Network Difficulty</div><div class='value code' id='m-diff'>--</div><div class='sub' id='m-diff-sub'>Difficulty snapshot</div></article>\n"
"      <article class='metric-card'><div class='label'>Latest Share</div><div class='value' id='m-latest-share'>--</div><div class='sub' id='m-latest-share-sub'>Last accepted share time</div></article>\n"
"      <article class='metric-card'><div class='label'>Connection Coverage</div><div class='value' id='m-coverage'>--</div><div class='sub' id='m-coverage-sub'>Subscribed / connected</div></article>\n"
"      <article class='metric-card'><div class='label'>Share Success</div><div class='value' id='m-share'>--</div><div class='sub' id='m-share-sub'>Valid / rejected totals</div></article>\n"
"      <article class='metric-card'><div class='label'>Block Acceptance</div><div class='value' id='m-block'>--</div><div class='sub' id='m-block-sub'>Accepted / submitted blocks</div></article>\n"
"      <article class='metric-card'><div class='label'>Best Share</div><div class='value code' id='m-best-share'>--</div><div class='sub' id='m-best-share-sub'>Highest accepted actual diff</div></article>\n"
"    </section>\n"
"    <section class='detail-grid'>\n"
"      <article class='panel'>\n"
"        <div class='panel-head'>\n"
"          <div>\n"
"            <h2>Operational Health</h2>\n"
"            <p>Derived directly from the current dashboard API snapshot, with emphasis on availability, share quality, and submission outcomes.</p>\n"
"          </div>\n"
"        </div>\n"
"        <div class='health-group'>\n"
"          <div class='health-top'><span>Subscriptions</span><strong id='health-sub-ratio'>--</strong></div>\n"
"          <div class='progress'><span id='bar-sub-ratio'></span></div>\n"
"          <p class='health-note' id='health-sub-note'>Waiting for connection data.</p>\n"
"        </div>\n"
"        <div class='health-group'>\n"
"          <div class='health-top'><span>Share Acceptance</span><strong id='health-share-ratio'>--</strong></div>\n"
"          <div class='progress'><span id='bar-share-ratio'></span></div>\n"
"          <p class='health-note' id='health-share-note'>Waiting for share history.</p>\n"
"        </div>\n"
"        <div class='health-group'>\n"
"          <div class='health-top'><span>Block Submission Success</span><strong id='health-block-ratio'>--</strong></div>\n"
"          <div class='progress'><span id='bar-block-ratio'></span></div>\n"
"          <p class='health-note' id='health-block-note'>Waiting for block submissions.</p>\n"
"        </div>\n"
"      </article>\n"
"      <article class='panel spotlight-panel'>\n"
"        <div class='panel-head'>\n"
"          <div>\n"
"            <h2>Best Share Since Launch</h2>\n"
"            <p>Tracks the highest accepted share actual difficulty observed across all miners since this process started.</p>\n"
"          </div>\n"
"        </div>\n"
"        <div class='best-share'>\n"
"          <div class='best-share-top'>\n"
"            <span>Highest Actual Diff</span>\n"
"            <strong class='code' id='best-share-diff'>--</strong>\n"
"          </div>\n"
"          <div class='best-share-meta'>\n"
"            <div><span>Miner</span><strong id='best-share-agent'>Loading first accepted share</strong></div>\n"
"            <div><span>Assigned Diff</span><strong class='code' id='best-share-assigned'>--</strong></div>\n"
"            <div><span>Submitted</span><strong id='best-share-time'>--</strong></div>\n"
"          </div>\n"
"        </div>\n"
"      </article>\n"
"    </section>\n"
"    <section class='section'>\n"
"      <div class='section-head'>\n"
"        <div>\n"
"          <div class='section-kicker'>Live Fleet</div>\n"
"          <h2>Connected Workers</h2>\n"
"          <p>Each card shows the worker user agent, estimated hashrate, best observed share difficulty, and relative fleet contribution.</p>\n"
"        </div>\n"
"        <div class='section-meta'>\n"
"          <span class='section-pill' id='worker-count'>Loading...</span>\n"
"          <span class='section-pill muted' id='worker-summary'>Waiting for worker metrics.</span>\n"
"        </div>\n"
"      </div>\n"
"      <div class='worker-grid' id='workers-list'>\n"
"        <div class='empty-state'><strong>Loading workers</strong><span>Subscribed miners will appear here once the API responds.</span></div>\n"
"      </div>\n"
"    </section>\n"
"    <section class='section'>\n"
"      <div class='section-head'>\n"
"        <div>\n"
"          <div class='section-kicker'>Recent Activity</div>\n"
"          <h2>Accepted Shares</h2>\n"
"          <p>The embedded API exposes the last ten accepted shares. Each strip keeps the assigned difficulty, actual share difficulty, and submit time visible without taking over the page.</p>\n"
"        </div>\n"
"        <div class='section-meta'>\n"
"          <span class='section-pill' id='share-count'>Loading...</span>\n"
"          <span class='section-pill muted' id='share-summary'>Waiting for share history.</span>\n"
"        </div>\n"
"      </div>\n"
"      <div class='share-list' id='shares-list'>\n"
"        <div class='empty-state'><strong>Loading shares</strong><span>Accepted shares will appear here after the first miner submissions.</span></div>\n"
"      </div>\n"
"    </section>\n"
"    <section class='section'>\n"
"      <div class='section-head'>\n"
"        <div>\n"
"          <div class='section-kicker'>Submission History</div>\n"
"          <h2>Found Blocks</h2>\n"
"          <p>Recent block submission results show the attempted height, block hash, and node response status for candidate blocks.</p>\n"
"        </div>\n"
"        <div class='section-meta'>\n"
"          <span class='section-pill' id='block-count'>Loading...</span>\n"
"          <span class='section-pill muted' id='block-summary'>Waiting for block records.</span>\n"
"        </div>\n"
"      </div>\n"
"      <div class='feed-list' id='blocks-list'>\n"
"        <div class='empty-state'><strong>Loading block history</strong><span>Submitted block candidates will appear here when available.</span></div>\n"
"      </div>\n"
"    </section>\n"
"    <footer class='foot'>\n"
"      <span>solo-mining-server embedded dashboard</span>\n"
"      <span id='footer-stamp'>Waiting for first refresh</span>\n"
"    </footer>\n"
"  </div>\n"
"</div>\n"
"<script>\n"
"var refreshBusy=false;\n"
"function byId(id){return document.getElementById(id)}\n"
"function num(v){var n=Number(v);return isFinite(n)?n:0}\n"
"function hasValue(v){return v!==null&&v!==undefined&&v!==''}\n"
"function fmtInt(v){return Math.round(num(v)).toLocaleString()}\n"
"function fmtFixed(v,d){return num(v).toFixed(d)}\n"
"function fmtDiff(v){var n=num(v),u=['','K','M','G','T','P','E','Z'],i=0;if(!n)return'0';while(n>=1000&&i<u.length-1){n/=1000;i++}return n.toFixed(n>=100?1:2)+u[i]}\n"
"function fmtHashrate(v){var n=num(v),sign=n<0?'-':'',abs=Math.abs(n),u=['H/s','kH/s','MH/s','GH/s','TH/s','PH/s','EH/s','ZH/s','YH/s'],i=0;if(!abs)return'--';while(abs>=1000&&i<u.length-1){abs/=1000;i++}return sign+abs.toFixed(abs>=100?1:2)+' '+u[i]}\n"
"function fmtCompact(v){var n=num(v),sign=n<0?'-':'',abs=Math.abs(n),u=['','K','M','G','T','P','E','Z','Y'],i=0;if(!abs)return'0';if(abs<1000)return fmtExact2(n);while(abs>=1000&&i<u.length-1){abs/=1000;i++}return sign+abs.toFixed(2)+u[i]}\n"
"function fmtExact2(v){var n=num(v),sign=n<0?'-':'',abs=Math.abs(n),scaled=Math.trunc(abs*100)/100,parts=scaled.toFixed(2).split('.');parts[0]=Number(parts[0]).toLocaleString();return sign+parts.join('.')}\n"
"function fmtPercentValue(v){return num(v).toFixed(1)+'%'}\n"
"function pct(part,total){part=num(part);total=num(total);return total>0?(part/total)*100:0}\n"
"function fmtDuration(total){var sec=Math.max(0,Math.floor(num(total))),days=Math.floor(sec/86400),hours,mins,parts=[];sec%=86400;hours=Math.floor(sec/3600);sec%=3600;mins=Math.floor(sec/60);sec%=60;if(days)parts.push(days+'d');if(hours||parts.length)parts.push(hours+'h');if(mins||parts.length)parts.push(mins+'m');parts.push(sec+'s');return parts.join(' ')}\n"
"function pad2(v){return String(v).padStart(2,'0')}\n"
"function fmtDateTime(ms){var d;if(!ms)return'--';d=new Date(ms);return d.getFullYear()+'-'+pad2(d.getMonth()+1)+'-'+pad2(d.getDate())+' '+pad2(d.getHours())+':'+pad2(d.getMinutes())+':'+pad2(d.getSeconds())}\n"
"function fmtRelative(ms){var sec,min,hr,day;if(!ms)return'Unavailable';sec=Math.max(0,Math.floor((Date.now()-num(ms))/1000));if(sec<5)return'just now';if(sec<60)return sec+'s ago';min=Math.floor(sec/60);if(min<60)return min+'m ago';hr=Math.floor(min/60);if(hr<24)return hr+'h ago';day=Math.floor(hr/24);if(day<7)return day+'d ago';return fmtDateTime(ms)}\n"
"function esc(s){var d=document.createElement('div');d.appendChild(document.createTextNode(s===null||s===undefined?'':String(s)));return d.innerHTML}\n"
"function escAttr(s){return esc(s).replace(/'/g,'&#39;')}\n"
"function shortAgent(agent){var raw=agent?String(agent):'Unknown',cut=raw.split(/[\\/\\s\\(]/)[0]||raw;if(cut.length<3)cut=raw;return cut.length>22?cut.slice(0,22)+'...':cut}\n"
"function shortHash(hash){var raw=hash?String(hash):'';return raw.length>28?raw.slice(0,14)+'...'+raw.slice(-12):raw}\n"
"function titleCase(text){var raw=text?String(text):'Unknown';return raw.replace(/_/g,' ').replace(/\\b\\w/g,function(ch){return ch.toUpperCase()})}\n"
"function barWidth(percent){var val=num(percent);if(val<=0)return'0%';return Math.max(8,Math.min(100,val)).toFixed(0)+'%'}\n"
"function setText(id,value){byId(id).textContent=value}\n"
"function setBar(id,value){byId(id).style.width=barWidth(value)}\n"
"function setStatus(tone,label,detail){byId('status-board').className='status-board'+(tone==='ok'?'':' '+tone);byId('status-dot').className='status-dot'+(tone==='ok'?'':' '+tone);setText('status-text',label);setText('status-note',detail)}\n"
"function normalizeArray(value){return Array.isArray(value)?value:[]}\n"
"function renderBestShare(stats){if(!stats.best_share_available){setText('best-share-diff','--');setText('best-share-agent','No accepted shares yet');setText('best-share-assigned','--');setText('best-share-time','Waiting for the first accepted share');return}setText('best-share-diff',fmtCompact(stats.best_share_actual_diff));setText('best-share-agent',stats.best_share_user_agent||'Unknown');setText('best-share-assigned',fmtInt(stats.best_share_difficulty));setText('best-share-time',fmtRelative(stats.best_share_timestamp_ms)+' / '+fmtDateTime(stats.best_share_timestamp_ms))}\n"
"function renderWorkers(workers,totalHash){var list=byId('workers-list'),maxHash=workers.length?num(workers[0].hashrate):0;if(!workers.length){list.innerHTML=\"<div class='empty-state'><strong>No active subscribed workers</strong><span>Connect a Stratum miner to start receiving live worker cards here.</span></div>\";return}list.innerHTML=workers.map(function(worker,index){var hash=num(worker.hashrate),share=totalHash>0?pct(hash,totalHash):0,meter=maxHash>0?(hash/maxHash)*100:0;return`<article class='worker-card'><div class='worker-head'><div><div class='rank'>Worker ${index+1}</div><h3 title='${escAttr(worker.user_agent||'Unknown')}'>${esc(shortAgent(worker.user_agent))}</h3></div><span class='badge-soft'>${fmtPercentValue(share)}</span></div><p class='worker-agent'>${esc(worker.user_agent||'Unknown')}</p><div class='meter'><span style='width:${barWidth(meter)}'></span></div><div class='worker-stats'><div><span>Hashrate</span><strong class='code'>${fmtFixed(hash,2)} TH/s</strong></div><div><span>Best Diff</span><strong class='code'>${fmtDiff(worker.best_diff)}</strong></div></div></article>`}).join('')}\n"
"function renderShares(shares){var list=byId('shares-list');if(!shares.length){list.innerHTML=\"<div class='empty-state'><strong>No accepted shares yet</strong><span>Recent accepted shares will appear here as miners submit valid work.</span></div>\";return}list.innerHTML=shares.map(function(share){var diff=num(share.difficulty),actual=num(share.actual_diff),quality=diff>0?actual/diff:0;return`<article class='share-strip'><div class='share-strip-main'><div class='share-strip-title'>${esc(shortAgent(share.user_agent))}</div><span class='share-strip-sub'>${esc(share.user_agent||'Unknown')}</span></div><div class='share-strip-stat'><span>Assigned</span><strong class='code'>${fmtInt(diff)}</strong></div><div class='share-strip-stat'><span>Actual</span><strong class='code'>${fmtDiff(actual)}</strong></div><div class='share-strip-stat'><span>Quality</span><strong class='code'>${fmtFixed(quality,2)}x</strong></div><div class='share-strip-time'>${esc(fmtRelative(share.timestamp_ms))}<br>${esc(fmtDateTime(share.timestamp_ms))}</div></article>`}).join('')}\n"
"function blockTone(result){var raw=result?String(result).toLowerCase():'unknown';if(raw==='submitted'||raw==='duplicate'||raw==='accepted')return'ok';if(raw==='confirm_failed'||raw==='unknown')return'warn';return'danger'}\n"
"function renderBlocks(blocks){var list=byId('blocks-list');if(!blocks.length){list.innerHTML=\"<div class='empty-state'><strong>No block records yet</strong><span>Submitted block candidates and their node responses will appear here.</span></div>\";return}list.innerHTML=blocks.map(function(block){var tone=blockTone(block.result);return`<article class='feed-item'><div class='feed-top'><div><div class='feed-title'>Height ${fmtInt(block.height)} <span class='status-pill ${tone}'>${esc(titleCase(block.result))}</span></div><span class='feed-sub'>Node response for a recent block candidate</span></div><div class='feed-time'>${esc(fmtRelative(block.timestamp_ms))}<br>${esc(fmtDateTime(block.timestamp_ms))}</div></div><div class='feed-grid'><div class='wide'><span>Block Hash</span><strong class='code' title='${escAttr(block.hash||'')}'>${esc(shortHash(block.hash||''))}</strong></div><div><span>Result</span><strong>${esc(titleCase(block.result))}</strong></div></div></article>`}).join('')}\n"
"function render(stats,workers,blocks,shares){var connections=num(stats.connections),subscriptions=num(stats.subscriptions),valid=num(stats.shares_valid),errors=num(stats.shares_error),shareTotal=valid+errors,submitted=num(stats.blocks_submitted),accepted=num(stats.blocks_accepted),totalHash=num(stats.hashrate_th_s),avgHash=subscriptions?totalHash/subscriptions:0,coverage=pct(subscriptions,connections),shareRate=pct(valid,shareTotal),blockRate=pct(accepted,submitted),templateAge=fmtRelative(stats.last_refresh_ms),heightText=hasValue(stats.current_height)?fmtInt(stats.current_height):'--',txnText=fmtInt(stats.txn_count),latestShare=shares.length?shares[0]:null,latestShareText=latestShare?fmtRelative(latestShare.timestamp_ms):'No shares',latestShareSub=latestShare?fmtDateTime(latestShare.timestamp_ms):'Waiting for first accepted share',bestShareText=stats.best_share_available?fmtCompact(stats.best_share_actual_diff):'--',bestShareSub=stats.best_share_available?'Assigned '+fmtInt(stats.best_share_difficulty)+' / '+fmtRelative(stats.best_share_timestamp_ms):'No accepted shares yet',freshAgeMs=stats.last_refresh_ms?Math.max(0,Date.now()-num(stats.last_refresh_ms)):0,tone='ok',statusLabel='Template Ready',statusDetail='Template refreshed '+templateAge;if(!stats.ready){tone='danger';statusLabel='Waiting For Template';statusDetail=stats.last_refresh_ok?'Template refresh succeeded but the job is not ready yet.':'Last template refresh has not succeeded yet.'}else if(!stats.last_refresh_ok||freshAgeMs>120000){tone='warn';statusLabel='Template Stale';statusDetail='Last template refresh was '+templateAge+'.'}setStatus(tone,statusLabel,statusDetail);setText('v-ver',stats.gateway_version||'--');setText('v-refresh-meta',templateAge);setText('v-hash',fmtFixed(totalHash,totalHash>=100?1:2)+' TH/s');setText('v-hash-sub',subscriptions?fmtFixed(avgHash,2)+' TH/s average':'Waiting for workers');setText('v-hash-note',shareTotal?fmtInt(shareTotal)+' total share decisions':'No share history yet');setText('v-workers',fmtInt(subscriptions));setText('v-workers-sub',fmtInt(connections)+' connected sockets');setText('v-workers-note',fmtPercentValue(coverage)+' of connections subscribed');setText('v-height',heightText);setText('v-height-sub',txnText+' transactions');setText('v-height-note',templateAge);setText('v-reward',fmtHashrate(stats.network_hashrate_hps));setText('v-reward-sub',fmtFixed(stats.current_value_btc,8)+' BTC');setText('v-reward-note',fmtDuration(stats.uptime_seconds));setText('m-sockets',fmtInt(connections));setText('m-sockets-sub',fmtInt(subscriptions)+' subscribed workers');setText('m-diff',fmtCompact(stats.network_difficulty));setText('m-diff-sub','Current network target difficulty');setText('m-latest-share',latestShareText);setText('m-latest-share-sub',latestShareSub);setText('m-coverage',fmtPercentValue(coverage));setText('m-coverage-sub',fmtInt(subscriptions)+' subscribed / '+fmtInt(connections)+' connected');setText('m-share',fmtPercentValue(shareRate));setText('m-share-sub',fmtInt(valid)+' valid / '+fmtInt(errors)+' rejected');setText('m-block',fmtPercentValue(blockRate));setText('m-block-sub',fmtInt(accepted)+' accepted / '+fmtInt(submitted)+' submitted');setText('m-best-share',bestShareText);setText('m-best-share-sub',bestShareSub);setText('health-sub-ratio',fmtPercentValue(coverage));setBar('bar-sub-ratio',coverage);setText('health-sub-note',subscriptions?fmtInt(subscriptions)+' subscribed workers across '+fmtInt(connections)+' open sockets.':'No subscribed workers yet.');setText('health-share-ratio',fmtPercentValue(shareRate));setBar('bar-share-ratio',shareRate);setText('health-share-note',shareTotal?fmtInt(valid)+' accepted shares against '+fmtInt(errors)+' rejects.':'No share history recorded yet.');setText('health-block-ratio',fmtPercentValue(blockRate));setBar('bar-block-ratio',blockRate);setText('health-block-note',submitted?fmtInt(accepted)+' of '+fmtInt(submitted)+' submitted blocks were accepted by the node.':'No full block submissions recorded yet.');setText('worker-count',subscriptions?fmtInt(subscriptions)+' active workers':'No active workers');setText('worker-summary',subscriptions?fmtFixed(avgHash,2)+' TH/s average per worker':'Waiting for subscribed miners.');setText('share-count',shares.length?fmtInt(shares.length)+' recent accepted shares':'No accepted shares');setText('share-summary',fmtInt(valid)+' valid / '+fmtInt(errors)+' rejected overall');setText('block-count',blocks.length?fmtInt(blocks.length)+' recent block records':'No block records');setText('block-summary',fmtInt(accepted)+' accepted / '+fmtInt(submitted)+' submitted overall');setText('footer-stamp','Updated '+fmtDateTime(Date.now()));renderBestShare(stats);renderWorkers(workers,totalHash);renderShares(shares);renderBlocks(blocks)}\n"
"async function fetchJson(url){var response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(url+' '+response.status);return response.json()}\n"
"async function refresh(){var stats,workers,blocks,shares;if(refreshBusy)return;refreshBusy=true;try{stats=await fetchJson('/api/stats');workers=await fetchJson('/api/workers').catch(function(){return[]});blocks=await fetchJson('/api/blocks').catch(function(){return[]});shares=await fetchJson('/api/shares').catch(function(){return[]});workers=normalizeArray(workers).filter(function(item){return item&&typeof item==='object'}).sort(function(a,b){return num(b.hashrate)-num(a.hashrate)});blocks=normalizeArray(blocks).filter(function(item){return item&&typeof item==='object'}).sort(function(a,b){return num(b.timestamp_ms)-num(a.timestamp_ms)});shares=normalizeArray(shares).filter(function(item){return item&&typeof item==='object'}).sort(function(a,b){return num(b.timestamp_ms)-num(a.timestamp_ms)});render(stats,workers,blocks,shares)}catch(err){setStatus('danger','Connection Error','Could not load /api/stats from the embedded server.');setText('v-refresh-meta','Offline');setText('best-share-diff','--');setText('best-share-agent','Dashboard API unavailable');setText('best-share-assigned','--');setText('best-share-time','--');setText('footer-stamp','Last refresh failed at '+fmtDateTime(Date.now()))}finally{refreshBusy=false}}\n"
"refresh();setInterval(refresh,5000);\n"
"</script>\n"
"</body>\n"
"</html>";

const char *web_get_html_dashboard(void)
{
    return html_dashboard;
}
